title: Cairn
permalink: pretty
remote_theme: pmarsceill/just-the-docs
site.url: https://cn.cairnrpg.com
logo: "/img/logo.png"
color_scheme: dark
encoding: UTF-8
plugins:
  - jekyll-redirect-from
include:
  - js

# Aux links for the upper right navigation
aux_links:
  "Github 仓库":
    - "https://github.com/ZzNoah/cairn-cn/"

# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: true
    
# External navigation links
nav_external_links:
  - title: Discord 频道
    url: https://discord.gg/K3dwaMap5X
    hide_icon: false
    opens_in_new_tab: true
  - title: 订阅新闻
    url: https://news.cairnrpg.com
    hide_icon: false
    opens_in_new_tab: true
  - title: 官方应用 kettlewright
    url: https://kettlewright.com/login
    hide_icon: false
    opens_in_new_tab: true

# Back to top link
back_to_top: true
back_to_top_text: "返回顶部"

footer_content: "本页文本基于 <a href=\"https://creativecommons.org/licenses/by-sa/4.0\">CC-BY-SA 4.0.</a> 许可协议"
# Footer last edited timestamp
last_edit_timestamp: true # show or hide edit time - page must have `last_modified_date` defined in the frontmatter
last_edit_time_format: "%b %e %Y at %I:%M %p" # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html

# If you want to ignore the monsters folder during builds
# exclude: /resources/monsters
